// <auto-generated />
namespace TellYourFriends.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update2CommentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update2CommentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201905241915536_update2CommentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
